name: Setup Swift
description: Setup a Swift environment on Ubuntu or macOS 
author: Frederik Wallner
inputs:
  swift-version: 
    description: Swift version to configure
    required: true
    default: '6.1.0'
  soft-fail-version-check:
    description: 'If true, unknown Swift versions will only warn instead of error'
    required: false
    default: 'false'
outputs:
  version:
    description: The full Swift version that was configured
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'command'  
  color: 'orange'
